name: Export Apptainer container for HPC

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Set SIF filename
        run: |
          DATE=$(date -u +%Y-%m-%d)
          SHA=${GITHUB_SHA::7}
          echo "SIF_NAME=diseasy-${DATE}-${SHA}.sif" >> "$GITHUB_ENV"

      - name: Install Apptainer
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt update
          sudo apt install -y apptainer
          apptainer version

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            apptainer registry login \
            --username "${{ github.actor }}" \
            --password-stdin \
            docker://ghcr.io

      - name: Create SIF
        run: |
          apptainer pull \
            "$SIF_NAME" \
            docker://ghcr.io/ssi-dk/diseasy:main

      - name: Inspect SIF
        run: |
          ls -lh "$SIF_NAME"
          apptainer inspect "$SIF_NAME"

      - name: Upload SIF
        uses: actions/upload-artifact@v4
        with:
          name: diseasy-apptainer
          path: ${{ env.SIF_NAME }}
          retention-days: 7
